/// <reference types="node" />
import { EventEmitter } from "events";
import { KeyCode } from "../keycode";
import { MonkeyCallback } from "..";
export default abstract class Api extends EventEmitter {
    abstract send(commands: string[] | string, cb?: Function): this;
    keyDown(keyCode: KeyCode | number, cb?: MonkeyCallback): this;
    keyUp(keyCode: KeyCode | number, cb?: MonkeyCallback): this;
    touchDown(x: number, y: number, cb?: MonkeyCallback): this;
    touchUp(x: number, y: number, cb?: MonkeyCallback): this;
    touchMove(x: number, y: number, cb?: MonkeyCallback): this;
    trackball(dx: number, dy: number, cb?: MonkeyCallback): this;
    flipOpen(cb?: MonkeyCallback): this;
    flipClose(cb?: MonkeyCallback): this;
    wake(cb?: MonkeyCallback): this;
    tap(x: number, y: number, cb?: MonkeyCallback): this;
    press(keyCode: KeyCode | number, cb?: MonkeyCallback): this;
    type(str: string, cb?: MonkeyCallback): this;
    list(cb?: MonkeyCallback<string[]>): this;
    get(name: string, cb?: MonkeyCallback): this;
    sleep(ms: number, cb?: MonkeyCallback): this;
    quit(cb?: MonkeyCallback): this;
    done(cb?: MonkeyCallback): this;
    getAmCurrentAction(cb?: MonkeyCallback): this;
    getAmCurrentCategories(cb?: MonkeyCallback): this;
    getAmCurrentCompClass(cb?: MonkeyCallback): this;
    getAmCurrentCompPackage(cb?: MonkeyCallback): this;
    getAmCurrentData(cb?: MonkeyCallback): this;
    getAmCurrentPackage(cb?: MonkeyCallback): this;
    getBuildBoard(cb?: MonkeyCallback): this;
    getBuildBrand(cb?: MonkeyCallback): this;
    getBuildCpuAbi(cb?: MonkeyCallback): this;
    getBuildDevice(cb?: MonkeyCallback): this;
    getBuildDisplay(cb?: MonkeyCallback): this;
    getBuildFingerprint(cb?: MonkeyCallback): this;
    getBuildHost(cb?: MonkeyCallback): this;
    getBuildId(cb?: MonkeyCallback): this;
    getBuildManufacturer(cb?: MonkeyCallback): this;
    getBuildModel(cb?: MonkeyCallback): this;
    getBuildProduct(cb?: MonkeyCallback): this;
    getBuildTags(cb?: MonkeyCallback): this;
    getBuildType(cb?: MonkeyCallback): this;
    getBuildUser(cb?: MonkeyCallback): this;
    getBuildVersionCodename(cb?: MonkeyCallback): this;
    getBuildVersionIncremental(cb?: MonkeyCallback): this;
    getBuildVersionRelease(cb?: MonkeyCallback): this;
    getBuildVersionSdk(cb?: MonkeyCallback): this;
    getClockMillis(cb?: MonkeyCallback): this;
    getClockRealtime(cb?: MonkeyCallback): this;
    getClockUptime(cb?: MonkeyCallback): this;
    getDisplayDensity(cb?: MonkeyCallback): this;
    getDisplayHeight(cb?: MonkeyCallback): this;
    getDisplayWidth(cb?: MonkeyCallback): this;
}
